# Generated by Django 3.1.1 on 2020-09-03 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mobil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(default='nama', max_length=100)),
                ('plat', models.CharField(default='000000', max_length=10)),
                ('gambar', models.ImageField(upload_to='upload_img/')),
                ('tipe', models.CharField(choices=[('Covertible', 'Covertible'), ('Coupe', 'Coupe'), ('Sedan', 'Sedan'), ('Hatchback', 'Hatchback'), ('SUV', 'SUV'), ('MPV', 'MPV')], default='MPV', max_length=20)),
                ('harga', models.IntegerField(default=100000)),
                ('deskripsi', models.TextField(default='deskripsi')),
            ],
        ),
    ]
