# Generated by Django 3.1.1 on 2020-09-11 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sewa_mobil', '0003_mobil_transmisi'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobil',
            name='gambar2',
            field=models.ImageField(default=1, upload_to='upload_img/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mobil',
            name='gambar3',
            field=models.ImageField(default=1, upload_to='upload_img/'),
            preserve_default=False,
        ),
    ]
