# Generated by Django 3.1.1 on 2020-09-11 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sewa_mobil', '0004_auto_20200911_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobil',
            name='gambar4',
            field=models.ImageField(default=1, upload_to='upload_img/'),
            preserve_default=False,
        ),
    ]
