# Generated by Django 3.1.1 on 2020-09-11 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sewa_mobil', '0005_mobil_gambar4'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobil',
            name='slug',
            field=models.SlugField(blank=True, editable=False),
        ),
    ]
