# Generated by Django 3.1.1 on 2020-09-15 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sewa_mobil', '0006_mobil_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pesanan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(default='nama', max_length=100)),
                ('plat', models.CharField(default='000000', max_length=10)),
                ('gambar', models.ImageField(upload_to='upload_img/')),
                ('harga', models.IntegerField(default=100000)),
                ('nama_user', models.CharField(max_length=50)),
                ('lama', models.IntegerField(max_length=2)),
                ('waktu_ambil', models.DateTimeField()),
                ('waktu_kembali', models.DateTimeField()),
            ],
        ),
    ]
