# Generated by Django 3.1.1 on 2020-09-15 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sewa_mobil', '0007_pesanan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesanan',
            name='lama',
            field=models.IntegerField(),
        ),
    ]
