# Generated by Django 3.1.1 on 2020-09-15 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sewa_mobil', '0009_auto_20200915_1540'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pesanan',
            old_name='waktu_ambil',
            new_name='tgl_kembali',
        ),
        migrations.RenameField(
            model_name='pesanan',
            old_name='waktu_kembali',
            new_name='tgl_pesan',
        ),
    ]
