# Generated by Django 3.1.1 on 2020-09-29 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sewa_mobil', '0010_auto_20200915_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesanan',
            name='total_bayar',
            field=models.IntegerField(default=0),
        ),
    ]
