# Generated by Django 3.1.1 on 2020-10-02 20:59

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sewa_mobil', '0013_mobil_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobil',
            name='rating',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, default=[]), size=None),
        ),
    ]
