# Generated by Django 3.1.1 on 2020-10-02 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sewa_mobil', '0014_auto_20201003_0359'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobil',
            name='rata_rating',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
